apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "sandbox-api.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sandbox-api.servolab.one
    http:
      paths:
      - backend:
          serviceName: {{ .Values.ingress.serviceName }}
          servicePort: 3002
        path: /helpers/
      - backend:
          serviceName: {{ .Values.ingress.serviceName }}
          servicePort: 3000
        path: /
  tls:
  - hosts:
    - sandbox-api.servolab.one
    secretName: sandbox-api.servolab.one-tls

