apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "sandbox-api.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: {{ template "sandbox-api.fullname" . }}
spec:
#  clusterIP: None
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  - name: "3002"
    port: 3002
    targetPort: 3002
  selector:
    app: {{ template "sandbox-api.fullname" . }}
status:
  loadBalancer: {}

